### ISSUE TITLE
Error during the obtaining 'js_code' - 'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by uninvisible** [Resheba/vk-video-download#4]
Seems, they changed something. Stated to receive an error:

```
    'NoneType' object has no attribute 'text'
```

https://github.com/Resheba/vk-video-download/blob/7bea691d3ec5934ef01268dfd0473b95f3a6931a/parserVK.py#L40

**Comment by Resheba** [comment]
Gruß!
Indeed, the layout of some elements has changed on the page.
Everything should be working properly at the moment.
Check last commit. ([ea475e3](https://github.com/Resheba/vk-video-download/commit/ea475e302be539f1e836dd99b757d942a8edf9f3))

If the problem is not solved, send new outputs.
Alles Gute!
